version: 0.2
run-as: root

phases:

  install:
    commands:
      - echo Installing app dependencies...
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.18.9/2020-11-02/bin/linux/amd64/kubectl   
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
      - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
      - source ~/.bashrc
      - echo 'Check kubectl version'
      - kubectl version --short --client
      - chmod +x prereqs.sh
     

  pre_build:
    commands:
      - echo Logging in to Amazon EKS...
      - aws eks --region ap-south-1 update-kubeconfig --name  eks-mumbai
      - echo check config 
      - kubectl config view --minify
      - echo check kubectl access
      - kubectl get svc
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 084138576643.dkr.ecr.ap-south-1.amazonaws.com
      - docker pull 084138576643.dkr.ecr.ap-south-1.amazonaws.com/code-build-nodeapp:latest
      

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t code-build-nodeapp . 
      - docker tag code-build-nodeapp:latest 084138576643.dkr.ecr.ap-south-1.amazonaws.com/code-build-nodeapp:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 084138576643.dkr.ecr.ap-south-1.amazonaws.com/code-build-nodeapp:latest
      - echo Push the latest image to cluster
      - kubectl apply -f node-deployment.yml
      - kubectl apply -f node-service.yml
      - kubectl rollout restart -f node-deployment.yml
